- name: Expense backend setup
  hosts: all
  become: yes
  tasks:
    - name: disable nodejs default version
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs 18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: copy backend service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: add application user
      ansible.builtin.user:
        name: expense

    - name: delete old app content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading and extracting the application code
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: install nodejs dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: app/

    - name: install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: load schema
      ansible.builtin.shell: mysql -h mysql-dev.praveendevops.online -uroot -p"{{ MYSQL_ROOT_PASSWORD }}"

    - name: reload, enable and restart service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes



